# Generated by Django 4.2.7 on 2025-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS gowheels_vehicle;"),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricing_type', models.CharField(choices=[('per-hour', 'Per Hour'), ('per-day', 'Per Day')], max_length=20)),
                ('category_image', models.ImageField(blank=True, upload_to='vehicles/category/')),
                ('brand_image', models.ImageField(blank=True, upload_to='vehicles/brand/')),
                ('model_image', models.ImageField(blank=True, upload_to='vehicles/model/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
