# Generated by Django 4.2.7 on 2025-12-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0007_vehicle_daily_end_range_vehicle_daily_start_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandimage',
            name='name',
            field=models.CharField(default='Brand Name', max_length=100),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='name',
            field=models.CharField(default='Model Name', max_length=100),
        ),
    ]
