# Generated by Django 4.2.7 on 2025-12-22 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0010_vehicle_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='gowheels.vehicle')),
            ],
        ),
    ]
