# Generated by Django 4.2.7 on 2025-12-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0012_category_update_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='unit_type',
            field=models.CharField(choices=[('unit_price', 'Unit Price'), ('square_feet', 'Square Feet'), ('cubic_feet', 'Cubic Feet')], default='unit_price', max_length=20),
        ),
    ]
