# Generated by Django 4.2.7 on 2025-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0015_vehicle_owner_name_vehicle_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='per_day_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='per_hour_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
