# Generated by Django 4.2.7 on 2026-01-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0018_pincode'),
    ]

    operations = [
    ]
