# Generated by Django 4.2.7 on 2026-01-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0019_auto_20260112_1834'),
    ]

    operations = [
    ]
