# Generated by Django 4.2.7 on 2026-01-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0020_auto_20260112_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_price_per_day', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('sponsor_price_per_day', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('promote', 'Promote'), ('sponsor', 'Sponsor')], max_length=20)),
                ('days', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='gowheels.vehicle')),
            ],
        ),
    ]
