from django.urls import path
from django.shortcuts import render
from . import views, api_views

urlpatterns = [
    path('', views.home, name='home'),
    path('phone-check/', views.phone_check, name='phone_check'),
    path('check-phone/', views.check_phone, name='check_phone'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('super-admin-login/', views.super_admin_login, name='super_admin_login'),
    path('super-admin-panel/', views.super_admin_panel, name='super_admin_panel'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('user-categories/', views.user_categories, name='user_categories'),
    path('browse-vehicles/', views.browse_vehicles, name='browse_vehicles'),
    path('logout/', views.logout_view, name='logout'),
    path('super-admin-logout/', views.super_admin_logout, name='super_admin_logout'),
    path('seller-dashboard/', views.seller_dashboard, name='seller_dashboard'),
    path('seller-dashboard-form/', views.seller_dashboard_form, name='seller_dashboard_form'),
    path('get-seller-vehicles/', views.get_seller_vehicles, name='get_seller_vehicles'),
    path('super-admin-categories/', views.super_admin_categories, name='super_admin_categories'),
    path('add-brands-models-form/', views.add_brands_models_form, name='add_brands_models_form'),
    path('add-model-to-brand/', views.add_model_to_brand, name='add_model_to_brand'),
    path('api/add-brands-models/', views.add_brands_models_api, name='add_brands_models_api'),
    path('api/add-model-to-brand/', views.add_model_to_brand_api, name='add_model_to_brand_api'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('api/get-user-profile/', views.get_user_profile_api, name='get_user_profile_api'),
    path('save-admin-data/', views.save_admin_data, name='save_admin_data'),
    path('get-admin-groups/', views.get_admin_groups, name='get_admin_groups'),
    path('get-all-admin-data/', views.get_all_admin_data, name='get_all_admin_data'),
    path('user-browse-categories/', views.user_browse_categories, name='user_browse_categories'),
    path('delete-vehicle/<int:vehicle_id>/', views.delete_vehicle, name='delete_vehicle'),
    path('edit-vehicle/<int:vehicle_id>/', views.edit_vehicle, name='edit_vehicle'),
    path('toggle-vehicle-status/<int:vehicle_id>/', views.toggle_vehicle_status, name='toggle_vehicle_status'),
    path('get-vehicles/', views.get_vehicles, name='get_vehicles'),
    path('track-vehicle-click/', views.track_vehicle_click, name='track_vehicle_click'),
    path('seller-vehicles/', views.seller_vehicles, name='seller_vehicles'),
    path('seller-complete-form/', lambda request: render(request, 'seller_complete_form.html'), name='seller_complete_form'),
    path('debug-video/', lambda request: render(request, 'debug_video_upload.html'), name='debug_video'),
    path('api/delete-admin-category/', views.delete_admin_category, name='delete_admin_category'),
    path('api/delete-admin-brand/', views.delete_admin_brand, name='delete_admin_brand'),
    path('api/delete-admin-model/', views.delete_admin_model, name='delete_admin_model'),
    path('api/get-all-users/', views.get_all_users_api, name='get_all_users_api'),
    path('api/block-user/<int:user_id>/', views.block_user, name='block_user'),
    
    # API URLs
    path('api/vehicles/', api_views.api_vehicles, name='api_vehicles'),
    path('api/user/<int:user_id>/', api_views.api_user_profile, name='api_user_profile'),
]