# Generated by Django 4.2.7 on 2026-01-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brands/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=20)),
                ('name', models.CharField(default='Brand Name', max_length=100)),
                ('image', models.ImageField(upload_to='brands/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group3', 'Group 3')], max_length=20)),
                ('image', models.ImageField(upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('hourly_start_range', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('hourly_end_range', models.DecimalField(decimal_places=2, default=3000, max_digits=8)),
                ('daily_start_range', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('daily_end_range', models.DecimalField(decimal_places=2, default=3000, max_digits=8)),
                ('per_day_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('per_hour_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('min_price', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('max_price', models.DecimalField(decimal_places=2, default=3000, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricing_type', models.CharField(choices=[('per-hour', 'Per Hour'), ('per-day', 'Per Day')], max_length=20)),
                ('unit_type', models.CharField(choices=[('unit_price', 'Unit Price'), ('square_feet', 'Square Feet'), ('cubic_feet', 'Cubic Feet')], default='unit_price', max_length=20)),
                ('category_image', models.ImageField(blank=True, upload_to='vehicles/category/')),
                ('brand_image', models.ImageField(blank=True, upload_to='vehicles/brand/')),
                ('model_image', models.ImageField(blank=True, upload_to='vehicles/model/')),
                ('seller_phone', models.CharField(blank=True, max_length=15)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('promoted', models.BooleanField(default=False)),
                ('sponsored', models.BooleanField(default=False)),
                ('added_by', models.CharField(default='super_admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='vehicles/seller/videos/')),
                ('duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gowheels.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/seller/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gowheels.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=15)),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='gowheels.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('pincode', models.CharField(max_length=10)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profiles/')),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_pincode', models.CharField(max_length=10)),
                ('nearby_pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('main_pincode', 'nearby_pincode')},
            },
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=20)),
                ('name', models.CharField(default='Model Name', max_length=100)),
                ('image', models.ImageField(upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='gowheels.brandimage')),
            ],
        ),
        migrations.AddField(
            model_name='brandimage',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='gowheels.category'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gowheels.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='gowheels.adminbrand')),
            ],
        ),
        migrations.CreateModel(
            name='AdminCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gowheels.admingroup')),
            ],
        ),
        migrations.AddField(
            model_name='adminbrand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='gowheels.admincategory'),
        ),
    ]
