# Generated by Django 4.2.26 on 2026-02-09 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0004_permission_userrole_userauthentication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_phone', models.CharField(max_length=15)),
                ('seller_phone', models.CharField(max_length=15)),
                ('last_message', models.TextField(blank=True)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('unread_buyer', models.IntegerField(default=0)),
                ('unread_seller', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_phone', models.CharField(max_length=15)),
                ('referral_code', models.CharField(max_length=10, unique=True)),
                ('referred_phone', models.CharField(blank=True, max_length=15)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 9, 13, 52, 47, 530789)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 2, 9, 13, 53, 51, 636024)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_hash',
            field=models.CharField(default=datetime.datetime(2026, 2, 9, 13, 54, 1, 483219), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'is_used'], name='gowheels_ot_phone_7bbfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='gowheels_ot_expires_201a4f_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gowheels.chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='gowheels.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('vehicle', 'buyer_phone')},
        ),
    ]
