# Generated by Django 4.2.7 on 2025-12-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0004_brandimage_modelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/seller/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gowheels.vehicle')),
            ],
        ),
    ]
