# Generated by Django 4.2.26 on 2026-02-09 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0005_chat_message_referral_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='gowheels.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_phone', 'vehicle')},
            },
        ),
    ]
