# Generated by Django 4.2.7 on 2025-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0005_vehicle_seller_phone_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='added_by',
            field=models.CharField(default='super_admin', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
