# Generated by Django 4.2.26 on 2026-02-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], default='rent', max_length=10),
        ),
    ]
