# Generated by Django 4.2.7 on 2025-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0006_vehicle_added_by_vehicle_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='daily_end_range',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='daily_start_range',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hourly_end_range',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hourly_start_range',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
