# Generated by Django 4.2.7 on 2025-12-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0008_brandimage_name_modelimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelimage',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='gowheels.brandimage'),
        ),
    ]
