# Generated by Django 4.2.7 on 2025-12-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0009_modelimage_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
