# Generated by Django 4.2.7 on 2025-12-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0014_adminbrand_admingroup_adminmodel_admincategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
