# Generated by Django 4.2.7 on 2025-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0016_vehicle_per_day_price_vehicle_per_hour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
