# Generated by Django 4.2.7 on 2026-01-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gowheels', '0017_userprofile_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='vehicles/seller/videos/')),
                ('duration', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gowheels.vehicle')),
            ],
        ),
    ]
